apiVersion: v1
kind: Service
metadata:
  name: mlperf-llama-service
  namespace: default
  labels:
    app: mlperf-llama
spec:
  selector:
    app: mlperf-llama
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: http
  type: ClusterIP