apiVersion: v1
kind: Secret
metadata:
  name: hf-token
  namespace: default
type: Opaque
data:
  # Replace with your base64 encoded HuggingFace token
  # echo -n "your_hf_token_here" | base64
  token: eW91cl9oZl90b2tlbl9oZXJl  # "your_hf_token_here" in base64