apiVersion: batch/v1
kind: Job
metadata:
  name: mlperf-benchmark-full
  labels:
    app: mlperf
    type: benchmark
    samples: "13368"
spec:
  backoffLimit: 2
  ttlSecondsAfterFinished: 86400  # Keep for 24 hours
  template:
    metadata:
      labels:
        app: mlperf
        type: benchmark
    spec:
      restartPolicy: Never
      tolerations:
      - key: nvidia.com/gpu
        operator: Exists
        effect: NoSchedule
      containers:
      - name: mlperf-benchmark
        image: mlperf-universal:latest  # Build this image from the Dockerfile
        imagePullPolicy: IfNotPresent
        command: ["/bin/bash"]
        args:
        - -c
        - |
          source /app/k8s-scripts/setup-cluster.sh
          exec /app/k8s-scripts/run-benchmark.sh
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        envFrom:
        - configMapRef:
            name: mlperf-config
        - secretRef:
            name: mlperf-secrets
            optional: true
        resources:
          requests:
            nvidia.com/gpu: 1
            memory: "16Gi"
            cpu: "4"
          limits:
            nvidia.com/gpu: 1
            memory: "32Gi"
            cpu: "8"
        volumeMounts:
        - name: shared-results
          mountPath: /shared
        - name: mlperf-scripts
          mountPath: /app/k8s-scripts
        - name: huggingface-cache
          mountPath: /root/.cache/huggingface
      volumes:
      - name: shared-results
        persistentVolumeClaim:
          claimName: mlperf-results-pvc
      - name: mlperf-scripts
        configMap:
          name: mlperf-scripts
          defaultMode: 0755
      - name: huggingface-cache
        persistentVolumeClaim:
          claimName: huggingface-cache-pvc

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mlperf-results-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
  storageClassName: nfs-client  # Adjust for your storage class

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: huggingface-cache-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  storageClassName: nfs-client  # Adjust for your storage class