apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlperf-llama
  namespace: default
  labels:
    app: mlperf-llama
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mlperf-llama
  template:
    metadata:
      labels:
        app: mlperf-llama
    spec:
      containers:
      - name: mlperf-llama
        image: jungwooshim/mlperf-llama:latest
        env:
        - name: HF_TOKEN
          valueFrom:
            secretKeyRef:
              name: hf-token
              key: token
        - name: CUDA_VISIBLE_DEVICES
          value: "0"
        resources:
          requests:
            memory: "8Gi"
            cpu: "2"
            nvidia.com/gpu: 1
          limits:
            memory: "16Gi"
            cpu: "4"
            nvidia.com/gpu: 1
        volumeMounts:
        - name: cache-volume
          mountPath: /app/cache
        - name: results-volume
          mountPath: /app/results
        ports:
        - containerPort: 8080
          name: http
      volumes:
      - name: cache-volume
        emptyDir:
          sizeLimit: 10Gi
      - name: results-volume
        emptyDir:
          sizeLimit: 5Gi
      nodeSelector:
        accelerator: nvidia-tesla-a30
      tolerations:
      - key: nvidia.com/gpu
        operator: Exists
        effect: NoSchedule