apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: ntp-sync
  namespace: kube-system
  labels:
    app: ntp-sync
spec:
  selector:
    matchLabels:
      app: ntp-sync
  template:
    metadata:
      labels:
        app: ntp-sync
    spec:
      hostNetwork: true
      hostPID: true
      containers:
      - name: ntp-sync
        image: ubuntu:22.04
        securityContext:
          privileged: true
        command:
        - /bin/bash
        - -c
        - |
          apt-get update && apt-get install -y ntp ntpdate
          # Configure NTP servers
          echo "server time.nist.gov iburst" >> /etc/ntp.conf
          echo "server pool.ntp.org iburst" >> /etc/ntp.conf
          # Stop systemd-timesyncd to avoid conflicts
          systemctl stop systemd-timesyncd
          systemctl disable systemd-timesyncd
          # Start NTP service
          service ntp start
          # Keep container running
          tail -f /var/log/ntp.log
        resources:
          requests:
            memory: "64Mi"
            cpu: "10m"
          limits:
            memory: "128Mi"
            cpu: "50m"
        volumeMounts:
        - name: etc-ntp
          mountPath: /etc/ntp.conf
          subPath: ntp.conf
        - name: var-log
          mountPath: /var/log
      volumes:
      - name: etc-ntp
        configMap:
          name: ntp-config
      - name: var-log
        hostPath:
          path: /var/log
      tolerations:
      - operator: Exists
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ntp-config
  namespace: kube-system
data:
  ntp.conf: |
    # NTP configuration for MLPerf benchmark synchronization
    driftfile /var/lib/ntp/ntp.drift
    
    # Time servers
    server time.nist.gov iburst
    server pool.ntp.org iburst
    server time.google.com iburst
    
    # Security settings
    restrict default kod notrap nomodify nopeer noquery
    restrict 127.0.0.1
    restrict ::1
    
    # Local clock as fallback
    server 127.127.1.0
    fudge 127.127.1.0 stratum 10